#!/usr/bin/env python3
#
# api/findmyvm

from cgi import FieldStorage
from re import match
import psycopg2
from json import dumps,loads

regex_ip = "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"
regex_mac = "^([0-9a-fA-F][0-9a-fA-F]:){5}([0-9a-fA-F][0-9a-fA-F])$"
regex_host = "^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$";
regex_num = "^[-+]?[0-9]+$"

form = FieldStorage()
dbconn = psycopg2.connect("dbname=findmyvmdb user=findmyvmuser")
cur=dbconn.cursor()
cur2=dbconn.cursor()

search_string = form["input"].value.strip()

best_guess = "VM Name"
limit_cond = "3"

try:
  if form["limit"].value:
    limit_cond = form["limit"].value
except:
  pass

try: 
  if form["fuzzy"].value:
    fuzzy_search="ON"
    if match(regex_ip, search_string):
      query_from = "nic_ipaddress"
      search_string1 = "%" + search_string + "%"
      search_string2 = "%" + search_string + "%;"
      best_guess = "IP Address"
    elif match(regex_mac, search_string):
      query_from = "nic_macaddress"
      search_string =  "%" + search_string + "%;"
      best_guess = "MAC Address"
    elif match(regex_num, search_string):
      query_from = "parent_name"
      search_string = "_%" + search_string + "%_"
      best_guess = "Deployment ID"
    else:
      query_from = "config_name"
      search_string = "%" + search_string + "%"
except: 
  fuzzy_search="OFF"
  if match(regex_ip, search_string):
    query_from = "nic_ipaddress"
    search_string1 = search_string 
    search_string2 = search_string + ";"
    best_guess = "IP Address"
  elif match(regex_mac, search_string):
    query_from = "nic_macaddress"
    search_string =  search_string + ";"
    best_guess = "MAC Address"
  elif match(regex_num, search_string):
    query_from = "parent_name"
    search_string = "%\_" + search_string + "\_%"
    best_guess = "Deployment ID"
  else:
    query_from = "config_name"

#SRM_VC = "'(drm|hop)r1%'"
SRM_VC="'%r1%'"

if query_from == "nic_ipaddress":
  cur.execute("SELECT * FROM vms WHERE nic_ipaddress ILIKE '%s' OR guest_ipaddress %s '%s' AND vc NOT SIMILAR TO %s ORDER BY scandate DESC LIMIT %s" % (search_string2, like_cond, search_string1, SRM_VC,limit_cond)) 
else:
  cur.execute("SELECT * FROM vms WHERE %s ILIKE '%s' AND VC NOT SIMILAR TO %s ORDER BY scandate DESC LIMIT %s" % (query_from, search_string, SRM_VC, limit_cond)) 

rows = cur.fetchall()

total_rows = len(rows)
current_row = 0 

colnames = [desc[0] for desc in cur.description]

jout = {}
jout['total'] = total_rows
jout['query'] = search_string
jout['best_guess'] = best_guess
jout['fuzzy'] = fuzzy_search
jout['results'] = {}
plainout=''

for row in rows:
  current_row +=1
  jout['results'][current_row]={}
  for x in range(len(row)):
    rowval = row[x]
    jout['results'][current_row][colnames[x]]=rowval
    if colnames[x] == 'runtime_host_name':
      try:
        cur2.execute("SELECT assettag from esxi where config_name = '%s' limit 1" % (rowval))
        assettag = cur2.fetchone()
        jout['results'][current_row]['assettag']=assettag[0]
      except:
        pass

try:
  output_format = form["format"].value
except:
  output_format = 'json'

if output_format == "plain":
  results_one = loads(dumps(jout['results'][1],default=str))
  print ("Content-Type: text/plain\n")
  for x in results_one:
     print ( "* %s: \"%s\"" % (x, results_one[x]))

else:
  print ("Content-Type: application/json\n")
  print (dumps(jout, indent=4, default=str))

cur.close()
dbconn.close()


