#!/usr/bin/env python3
#
from json import dumps,load
from ipaddress import ip_address, ip_network
from cgi import FieldStorage
from re import match

regex_ip4 = "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"
regex_ip6 = "(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))"
form = FieldStorage()

print ("Content-Type: application/json\n")

try: 
  search_string = form["input"].value.strip()
  if match(regex_ip4, search_string) or match(regex_ip6, search_string):
    f=open('/var/www/roweb/findmyvm/networks.json','r')
    json_data = load(f)
    f.close()
    results = {}
    extattrs2 = {}

    for i in range(len(json_data)):
      if ip_address(search_string) in ip_network(json_data[i]["network"]):
        results = json_data[i]

    if results:
      for key in results['extattrs']:
        extattrs2[key] = results['extattrs'][key]['value']
      del results['extattrs']
      for key in extattrs2:
        results[key] = extattrs2[key]

  print (dumps(results, indent=4))

except:
  pass
